import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from 'next/image';
import Link from 'next/link';
import MobileNav from "./MobileNav";
import ClientProviders from "./components/ClientProviders";
import Script from 'next/script';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics */}
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-XXXXXXX');
          `}
        </Script>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Supercharge your business with next-gen AI chatbots and automation. Connect, automate, and grow with GoConnect." />
        <meta property="og:title" content="GoConnect - AI Automation, Reimagined" />
        <meta property="og:description" content="Supercharge your business with next-gen AI chatbots and automation." />
        <meta property="og:image" content="/logo.png" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://goconnect.com" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="GoConnect - AI Automation, Reimagined" />
        <meta name="twitter:description" content="Supercharge your business with next-gen AI chatbots and automation." />
        <meta name="twitter:image" content="/logo.png" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://cdn.botpress.cloud" />
        <link rel="dns-prefetch" href="https://cdn.botpress.cloud" />
      </head>
      <body className="bg-black text-white min-h-screen">
        <ClientProviders>
          <nav className="sticky top-0 z-50 bg-black bg-opacity-80 backdrop-blur flex items-center justify-between px-4 md:px-6 py-3 shadow-lg">
            <Link href="/">
              <div className="flex items-center gap-2">
                <Image src="/logo.png" alt="GoConnect Logo" width={48} height={48} priority />
                <span className="text-2xl font-bold tracking-tight text-green-400">GOCONNECT</span>
              </div>
            </Link>
            <MobileNav />
            <div className="hidden md:flex gap-6 text-lg font-medium items-center">
              <Link href="/about" className="hover:text-green-400 transition">About</Link>
              <Link href="/services" className="hover:text-green-400 transition">Services</Link>
              <Link href="/pricing" className="hover:text-green-400 transition">Pricing</Link>
              <Link href="/testbot" className="hover:text-green-400 transition">Real Estate Bot</Link>
              <Link href="/property-manager-bot" className="hover:text-green-400 transition">Property Manager Bot</Link>
              <Link href="/how-it-works" className="hover:text-green-400 transition">How It Works</Link>
              <Link href="/contact" className="hover:text-green-400 transition">Contact</Link>
            </div>
          </nav>
          <main className="pt-6">{children}</main>
          <footer className="mt-12 bg-black bg-opacity-90 border-t border-green-900 text-gray-300 px-4 md:px-6 py-10 flex flex-col md:flex-row md:justify-between gap-8">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <Image src="/logo.png" alt="GoConnect Logo" width={32} height={32} />
                <span className="text-xl font-bold text-green-400">GOCONNECT</span>
              </div>
              <p className="max-w-xs text-sm mb-2">Supercharge your business with next-gen AI chatbots and automation.</p>
              <div className="flex gap-4 mt-2">
                <a href="https://wa.me/447488813254" aria-label="WhatsApp" target="_blank" rel="noopener noreferrer" className="hover:text-green-400 transition">
                  {/* WhatsApp icon */}
                  <svg width="24" height="24" fill="currentColor" viewBox="0 0 32 32"><path d="M16 3C9.373 3 4 8.373 4 15c0 2.385.832 4.584 2.236 6.37L4 29l7.824-2.05A12.94 12.94 0 0 0 16 27c6.627 0 12-5.373 12-12S22.627 3 16 3zm0 22.917c-2.09 0-4.13-.547-5.89-1.583l-.42-.25-4.65 1.22 1.24-4.54-.27-.43A10.93 10.93 0 0 1 5 15c0-6.065 4.935-11 11-11s11 4.935 11 11-4.935 11-11 11zm5.29-7.13c-.29-.15-1.71-.84-1.97-.94-.26-.1-.45-.15-.64.15-.19.29-.74.94-.91 1.13-.17.19-.33.2-.61.07-.29-.14-1.23-.45-2.36-1.5-.87-.77-1.45-1.71-1.62-2-.17-.29-.02-.45.13-.59.13-.13.3-.34.44-.51.15-.17.19-.3.29-.49.1-.19.05-.36-.02-.5-.08-.14-.64-1.54-.88-2.1-.23-.56-.47-.48-.64-.49-.17-.01-.36-.01-.54-.01-.19 0-.5.08-.76.36-.26.28-1.01 1-1.01 2.41 0 1.41 1.03 2.77 1.18 2.96.15.19 2.04 3.12 4.95 4.25.69.29 1.23.47 1.65.6.69.22 1.31.19 1.8.12.55-.08 1.72-.7 1.97-1.38.24-.68.24-1.25.17-1.38-.07-.13-.26-.19-.56-.34z"/></svg>
                </a>
                <a href="https://www.facebook.com/goconnect234" aria-label="Facebook" target="_blank" rel="noopener noreferrer" className="hover:text-green-400 transition">
                  {/* Facebook icon */}
                  <svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M22.675 0h-21.35C.592 0 0 .592 0 1.326v21.348C0 23.408.592 24 1.325 24h11.495v-9.294H9.692v-3.622h3.128V8.413c0-3.1 1.893-4.788 4.659-4.788 1.325 0 2.463.099 2.797.143v3.24l-1.918.001c-1.504 0-1.797.715-1.797 1.763v2.312h3.587l-.467 3.622h-3.12V24h6.116C23.408 24 24 23.408 24 22.674V1.326C24 .592 23.408 0 22.675 0"/></svg>
                </a>
                <a href="https://x.com/goconnect234" aria-label="X (Twitter)" target="_blank" rel="noopener noreferrer" className="hover:text-green-400 transition">
                  {/* X (Twitter) icon */}
                  <svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M17.53 2.47 12 10.07 6.47 2.47H2.47l7.07 9.46L2.47 21.53h4l5.53-7.6 5.53 7.6h4l-7.07-9.6 7.07-9.46z"/></svg>
                </a>
                <a href="https://www.instagram.com/goconnect1" aria-label="Instagram" target="_blank" rel="noopener noreferrer" className="hover:text-green-400 transition">
                  {/* Instagram icon */}
                  <svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 1.366.062 2.633.334 3.608 1.308.974.974 1.246 2.242 1.308 3.608.058 1.266.07 1.646.07 4.85s-.012 3.584-.07 4.85c-.062 1.366-.334 2.633-1.308 3.608-.974.974-2.242 1.246-3.608 1.308-1.266.058-1.646.07-4.85.07s-3.584-.012-4.85-.07c-1.366-.062-2.633-.334-3.608-1.308-.974-.974-1.246-2.242-1.308-3.608C2.175 15.647 2.163 15.267 2.163 12s.012-3.584.07-4.85c.062-1.366.334-2.633 1.308-3.608C4.515 2.497 5.783 2.225 7.149 2.163 8.415 2.105 8.795 2.163 12 2.163zm0-2.163C8.736 0 8.332.012 7.052.07 5.77.128 4.87.312 4.1.54c-.77.23-1.42.54-2.07 1.19-.65.65-.96 1.3-1.19 2.07-.23.77-.412 1.67-.47 2.95C.012 8.332 0 8.736 0 12c0 3.264.012 3.668.07 4.948.058 1.282.24 2.182.47 2.95.23.77.54 1.42 1.19 2.07.65.65 1.3.96 2.07 1.19.77.23 1.67.412 2.95.47C8.332 23.988 8.736 24 12 24s3.668-.012 4.948-.07c1.282-.058 2.182-.24 2.95-.47.77-.23 1.42-.54 2.07-1.19.65-.65.96-1.3 1.19-2.07.23-.77.412-1.67.47-2.95.058-1.28.07-1.684.07-4.948s-.012-3.668-.07-4.948c-.058-1.282-.24-2.182-.47-2.95-.23-.77-.54-1.42-1.19-2.07-.65-.65-1.3-.96-2.07-1.19-.77-.23-1.67-.412-2.95-.47C15.668.012 15.264 0 12 0zm0 5.838a6.162 6.162 0 1 0 0 12.324 6.162 6.162 0 0 0 0-12.324zm0 10.162a3.999 3.999 0 1 1 0-7.998 3.999 3.999 0 0 1 0 7.998zm7.844-10.406a1.44 1.44 0 1 1-2.88 0 1.44 1.44 0 0 1 2.88 0z"/></svg>
                </a>
                <a href="https://www.tiktok.com/@goconnect10" aria-label="TikTok" target="_blank" rel="noopener noreferrer" className="hover:text-green-400 transition">
                  {/* TikTok icon */}
                  <svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2C6.477 2 2 6.477 2 12c0 5.523 4.477 10 10 10s10-4.477 10-10c0-5.523-4.477-10-10-10zm4.5 8.5v5.25a4.75 4.75 0 1 1-4.75-4.75h1.25v2.25h-1.25a2.5 2.5 0 1 0 2.5 2.5V6.5h2.25a2.25 2.25 0 0 0 2.25 2.25z"/></svg>
                </a>
              </div>
            </div>
            <div className="flex flex-col gap-2 text-sm">
              <span className="font-semibold text-green-400 mb-1">Quick Links</span>
              <a href="/blog" className="hover:text-green-400 transition">Blog</a>
              <a href="/faq" className="hover:text-green-400 transition">FAQ</a>
              <a href="/testimonials" className="hover:text-green-400 transition">Testimonials</a>
              <a href="/careers" className="hover:text-green-400 transition">Careers</a>
              <a href="/privacy-policy" className="hover:text-green-400 transition">Privacy Policy</a>
              <a href="/terms" className="hover:text-green-400 transition">Terms of Service</a>
            </div>
            <div className="flex flex-col gap-2 text-sm">
              <span className="font-semibold text-green-400 mb-1">Contact</span>
              <span>Email: <a href="mailto:goconnect@goconnect.space" className="hover:text-green-400 transition">goconnect@goconnect.space</a></span>
            </div>
          </footer>
        </ClientProviders>
      </body>
    </html>
  );
}
