import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from 'next/image';
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-black text-white min-h-screen">
        <nav className="sticky top-0 z-50 bg-black bg-opacity-80 backdrop-blur flex items-center justify-between px-6 py-3 shadow-lg">
          <Link href="/">
            <div className="flex items-center gap-2">
              <Image src="/logo.png" alt="GoConnect Logo" width={48} height={48} priority />
              <span className="text-2xl font-bold tracking-tight text-green-400">GOCONNECT</span>
            </div>
          </Link>
          <div className="flex gap-6 text-lg font-medium">
            <Link href="/about" className="hover:text-green-400 transition">About</Link>
            <Link href="/services" className="hover:text-green-400 transition">Services</Link>
            <Link href="/how-it-works" className="hover:text-green-400 transition">How It Works</Link>
            <Link href="/contact" className="hover:text-green-400 transition">Contact</Link>
          </div>
        </nav>
        <main className="pt-6">{children}</main>
      </body>
    </html>
  );
}
